---

- name: Creates directory 
  file:
    path: ~/backend
    state: directory

- name: "Extract artifact"
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: ~/backend

- name: "Install node_modules"
  shell: |
    cd ~/backend
    npm i

- name: "Stop app"
  shell: |
    cd ~/backend
    pm2 stop default || true

- name: "List app"
  shell: |
    cd ~/backend
    pm2 list

- name: "Start app"
  shell: |
    cd ~/backend
    pm2 start npm -- start

- name: "List app after"
  shell: |
    cd ~/backend
    pm2 list
