---

- name: "Extract artifact"
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: .

- name: "Install node_modules"
  shell: |
    npm i

- name: start app
  become: yes
  shell: |
    pm2 stop all
    pm2 start npm -- start
